cmake_minimum_required(VERSION 4.2)
project(DataStructures)

set(CMAKE_CXX_STANDARD 20)

add_definitions(-D ACM_LOCAL)

add_executable(DataStructures
        main.cpp)
target_link_libraries(DataStructures)

add_executable(WD_02_LinkedList_02_BasicOperations_LinkedList_BasicOps
        WangDao_2027/02_LinkedList/02_BasicOperations/linked_list_basic_ops.cpp)
target_link_libraries(WD_02_LinkedList_02_BasicOperations_LinkedList_BasicOps)

add_executable(WD_01_SequentialList_02_QuickSort_02_QuickSort
        WangDao_2027/01_SequentialList/02_QuickSort/02_QuickSort.cpp)
target_compile_definitions(WD_01_SequentialList_02_QuickSort_02_QuickSort PRIVATE RUN_QIUCKSORT_WD)

add_executable(WD_01_SequentialList_04_OptimizedSolution_01_BinarySearch_template1_equivalent
        WangDao_2027/01_SequentialList/04_OptimizedSolution/01_BinarySearch/template1_equivalent.cpp)
target_compile_definitions(WD_01_SequentialList_04_OptimizedSolution_01_BinarySearch_template1_equivalent PRIVATE RUN_TEMPLATE1_EQUIVALENT_WD)

add_executable(WD_01_SequentialList_04_OptimizedSolution_01_BinarySearch_template2_interval
        WangDao_2027/01_SequentialList/04_OptimizedSolution/01_BinarySearch/template2_interval.cpp)
target_compile_definitions(WD_01_SequentialList_04_OptimizedSolution_01_BinarySearch_template2_interval PRIVATE RUN_TEMPLATE2_INTERVAL_WD)

add_executable(WD_01_SequentialList_04_OptimizedSolution_03_preprocessing_2_6_On_Kadane_Kadane
        WangDao_2027/01_SequentialList/04_OptimizedSolution/03_preprocessing/2_6_On_Kadane/Kadane.cpp)
target_compile_definitions(WD_01_SequentialList_04_OptimizedSolution_03_preprocessing_2_6_On_Kadane_Kadane PRIVATE RUN_KADANE_WD)

add_executable(WD_01_SequentialList_04_OptimizedSolution_03_preprocessing_fixed_length_max_subarray
        WangDao_2027/01_SequentialList/04_OptimizedSolution/03_preprocessing/fixed_length_max_subarray.cpp)
target_compile_definitions(WD_01_SequentialList_04_OptimizedSolution_03_preprocessing_fixed_length_max_subarray PRIVATE RUN_FIXED_LENGTH_MAX_SUBARRAY_WD)

add_executable(WD_01_SequentialList_04_OptimizedSolution_04_MultiPointerTechnique_quickselect_split_half
        WangDao_2027/01_SequentialList/04_OptimizedSolution/04_MultiPointerTechnique/quickselect_split_half.cpp)
target_compile_definitions(WD_01_SequentialList_04_OptimizedSolution_04_MultiPointerTechnique_quickselect_split_half PRIVATE RUN_MULTIPOINTERTECHNIQUE_WD)
